# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{pegasus}
  s.version = "0.0.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joe Edelman"]
  s.date = %q{2011-03-10}
  s.default_executable = %q{pegasus}
  s.description = %q{pegasus: unicorn-steady, redis-backed, shared-nothing worker processes}
  s.email = %q{joe@citizenlogistics.com}
  s.executables = ["pegasus"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/pegasus",
     "lib/pegasus.rb",
     "lib/pegasus/service.rb",
     "lib/pegasus/service/class_methods.rb",
     "lib/pegasus/service/instance_methods.rb",
     "test/helper.rb",
     "test/test_pegasus.rb"
  ]
  s.homepage = %q{http://github.com/citizenlogistics/pegasus}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{pegasus: unicorn-steady, redis-backed, shared-nothing worker processes}
  s.test_files = [
    "test/helper.rb",
     "test/test_pegasus.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<configurer>, [">= 0"])
      s.add_runtime_dependency(%q<unicorn_horn>, [">= 0"])
    else
      s.add_dependency(%q<configurer>, [">= 0"])
      s.add_dependency(%q<unicorn_horn>, [">= 0"])
    end
  else
    s.add_dependency(%q<configurer>, [">= 0"])
    s.add_dependency(%q<unicorn_horn>, [">= 0"])
  end
end

